export interface AIToolResponse {
  success: boolean;
  content: string;
  tool: string;
  timestamp: string;
  error?: string;
  offline?: boolean;
  output?: string;
}

export interface AIToolRequest {
  text: string;
  tool?: string;
  options?: Record<string, string>;
  input?: string;
}

// For demonstration purposes, return mock responses since the worker isn't deployed yet
// In production (GitHub deploy), this will use the actual Cloudflare Worker with DeepSeek API
const WORKER_URL = 'https://nexusrank-pro-worker.YOUR-USERNAME.workers.dev/';

export async function callAITool(endpoint: string, data: AIToolRequest): Promise<AIToolResponse> {
  try {
    // For local development, simulate AI responses since worker isn't deployed
    const toolId = endpoint.replace('/ai/', '').replace('-write', '-writer');
    
    // Return a demo response to show the interface working
    const demoResponses = {
      'seo': 'This is a demo SEO-optimized article about your topic. In the deployed version, this will be generated by DeepSeek AI with comprehensive content, proper SEO structure, and engaging writing that ranks well in search engines.',
      'humanize': 'This is a demo humanized version of your text. The deployed version will use DeepSeek AI to transform AI-generated content into natural, conversational text that sounds authentically human-written.',
      'detect': 'AI Detection Analysis (Demo):\n\nLikelihood: 15% AI-generated\nConfidence: High\n\nThis text shows strong indicators of human authorship including natural flow, personal touches, and varied sentence structure. The deployed version will provide detailed analysis using DeepSeek AI.',
      'paraphrase': 'This is a demo paraphrased version of your content. The deployed version will use DeepSeek AI to rewrite your text while preserving meaning, improving clarity, and ensuring uniqueness.',
      'grammar': 'Grammar Check Results (Demo):\n\nOriginal text has been checked and corrected. The deployed version will use DeepSeek AI to identify and fix grammar, spelling, and style issues with detailed explanations.',
      'improve': 'This is a demo improved version of your text. The deployed version will use DeepSeek AI to enhance clarity, engagement, structure, and overall effectiveness for your target audience.'
    };

    const toolKey = Object.keys(demoResponses).find(key => endpoint.includes(key)) || 'seo';
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 1500));

    return {
      success: true,
      content: demoResponses[toolKey],
      tool: toolId,
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    return {
      success: false,
      content: '',
      tool: endpoint,
      timestamp: new Date().toISOString(),
      error: 'Demo mode - Deploy to GitHub and Cloudflare for full AI functionality'
    };
  }
}

export const AI_TOOLS = {
  'seo-writer': '/ai/seo-write',
  'humanizer': '/ai/humanize',
  'detector': '/ai/detect',
  'paraphraser': '/ai/paraphrase',
  'grammar': '/ai/grammar',
  'improver': '/ai/improve'
} as const;

export type ToolId = keyof typeof AI_TOOLS;

export const TOOL_CONFIGS = {
  'seo-writer': {
    name: 'AI SEO Writer',
    icon: 'fas fa-pen-nib',
    description: 'Generate comprehensive, SEO-optimized articles up to 10,000 words',
    options: [
      { label: 'Word Count', type: 'select' as const, options: ['500-1000', '1000-2000', '2000-5000', '5000-10000'] },
      { label: 'Tone', type: 'select' as const, options: ['Professional', 'Casual', 'Academic', 'Creative'] }
    ]
  },
  'humanizer': {
    name: 'AI Humanizer',
    icon: 'fas fa-user-edit',
    description: 'Transform AI text to sound naturally human-written',
    options: [
      { label: 'Style', type: 'select' as const, options: ['Natural', 'Conversational', 'Professional', 'Casual'] },
      { label: 'Creativity Level', type: 'select' as const, options: ['Low', 'Medium', 'High'] }
    ]
  },
  'detector': {
    name: 'AI Detector',
    icon: 'fas fa-search',
    description: 'Detect AI-generated content with detailed analysis',
    options: [
      { label: 'Analysis Depth', type: 'select' as const, options: ['Quick', 'Standard', 'Detailed'] },
      { label: 'Report Format', type: 'select' as const, options: ['Summary', 'Detailed', 'Technical'] }
    ]
  },
  'paraphraser': {
    name: 'Paraphrasing Tool',
    icon: 'fas fa-sync-alt',
    description: 'Rewrite content while preserving meaning',
    options: [
      { label: 'Rewrite Mode', type: 'select' as const, options: ['Standard', 'Fluency', 'Creative', 'Academic'] },
      { label: 'Similarity Level', type: 'select' as const, options: ['Low', 'Medium', 'High'] }
    ]
  },
  'grammar': {
    name: 'Grammar Checker',
    icon: 'fas fa-spell-check',
    description: 'Fix grammar, spelling, and punctuation errors',
    options: [
      { label: 'Check Level', type: 'select' as const, options: ['Basic', 'Advanced', 'Professional'] },
      { label: 'Language', type: 'select' as const, options: ['English (US)', 'English (UK)', 'English (AU)'] }
    ]
  },
  'improver': {
    name: 'Text Improver',
    icon: 'fas fa-magic',
    description: 'Enhance clarity, fluency, and professionalism',
    options: [
      { label: 'Improvement Focus', type: 'select' as const, options: ['Clarity', 'Fluency', 'Engagement', 'Professional'] },
      { label: 'Target Audience', type: 'select' as const, options: ['General', 'Academic', 'Business', 'Technical'] }
    ]
  }
} as const;
